---
title: "DA 460 - Assignment 7"
author: "Marjorie Blanco"
date: "`r format(Sys.time(), '%d %B, %Y')`"`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Handout 7 R: Inference for categorical data


### Exercise 1
In the first paragraph, several key findings are reported. Do these percentages appear to be sample statistics (derived from the data sample) or population parameters?

### Exercise 2
The title of the report is "Global Index of Religiosity and Atheism". To generalize the report's findings to the global human population, what must we assume about the sampling method? Does that seem like a reasonable assumption?


## The data


download.file("http://www.openintro.org/stat/data/atheism.RData", destfile = "atheism.RData")
load("atheism.RData")

### Exercise 3

What does each row of Table 6 correspond to? What does each row of atheism correspond to?

To investigate the link between these two ways of organizing this data, take a look at the estimated proportion of atheists in the United States. Towards the bottom of Table 6, we see that this is 5%. We should be able to come to the same number using the atheism data.

### Exercise 4

Using the command below, create a new dataframe called us12 that contains only the rows in atheism associated with respondents to the 2012 survey from the United States. Next, calculate the proportion of atheist responses. Does it agree with the percentage in Table 6? If not, why?
us12 <- subset(atheism, nationality == "United States" & year == "2012")


## Inference on proportions

As was hinted at in Exercise 1, Table 6 provides statistics, that is, calculations made from the sample of 51,927 people. What we'd like, though, is insight into the population parameters. You answer the question, "What proportion of people in your sample reported being atheists?" with a statistic; while the question "What proportion of people on earth would report being atheists" is answered with an estimate of the parameter.

The inferential tools for estimating population proportion are analogous to those used for means in the last chapter: the confidence interval and the hypothesis test.
Exercise 5Write out the conditions for inference to construct a 95% confidence interval for the proportion of atheists in the United States in 2012. Are you confident all conditions are met?

If the conditions for inference are reasonable, we can either calculate the standard error and construct the interval by hand, or allow the inference function to do it for us.
inference(us12$response, est = "proportion", type = "ci", method = "theoretical", 
          success = "atheist")

Note that since the goal is to construct an interval estimate for a proportion, it's necessary to specify what constitutes a "success", which here is a response of "atheist".

Although formal confidence intervals and hypothesis tests don't show up in the report, suggestions of inference appear at the bottom of page 7: "In general, the error margin for surveys of this kind is ± 
±
 3-5% at 95% confidence".

### Exercise 6
Based on the R output, what is the margin of error for the estimate of the proportion of the proportion of atheists in US in 2012?

### Exercise 7
Using the inference function, calculate confidence intervals for the proportion of atheists in 2012 in two other countries of your choice, and report the associated margins of error. Be sure to note whether the conditions for inference are met. It may be helpful to create new data sets for each of the two countries first, and then use these data sets in the inference function to construct the confidence intervals.



How does the proportion affect the margin of error?

Imagine you've set out to survey 1000 people on two questions: are you female? and are you left-handed? Since both of these sample proportions were calculated from the same sample size, they should have the same margin of error, right? Wrong! While the margin of error does change with sample size, it is also affected by the proportion.

Think back to the formula for the standard error: SE=p(1???p)/n ??? ??? ??? ??? ??? ??? ??? ??? ???  ???  
SE=p(1???p)/n
. This is then used in the formula for the margin of error for a 95% confidence interval: ME=1.96×SE=1.96×p(1???p)/n ??? ??? ??? ??? ??? ??? ??? ??? ???  ???  
ME=1.96×SE=1.96×p(1???p)/n
. Since the population proportion p 
p
 is in this ME 
ME
 formula, it should make sense that the margin of error is in some way dependent on the population proportion. We can visualize this relationship by creating a plot of ME 
ME
 vs. p 
p
.

The first step is to make a vector p that is a sequence from 0 to 1 with each number separated by 0.01. We can then create a vector of the margin of error (me) associated with each of these values of p using the familiar approximate formula (ME=2×SE 
ME=2×SE
). Lastly, we plot the two vectors against each other to reveal their relationship.
n <- 1000
p <- seq(0, 1, 0.01)
me <- 2 * sqrt(p * (1 - p)/n)
plot(me ~ p, ylab = "Margin of Error", xlab = "Population Proportion")
Exercise 8Describe the relationship between p and me.


Success-failure condition

The textbook emphasizes that you must always check conditions before making inference. For inference on proportions, the sample proportion can be assumed to be nearly normal if it is based upon a random sample of independent observations and if both np???10 
np???10
 and n(1???p)???10 
n(1???p)???10
. This rule of thumb is easy enough to follow, but it makes one wonder: what's so special about the number 10?

The short answer is: nothing. You could argue that we would be fine with 9 or that we really should be using 11. What is the "best" value for such a rule of thumb is, at least to some degree, arbitrary. However, when np 
np
 and n(1???p) 
n(1???p)
 reaches 10 the sampling distribution is sufficiently normal to use confidence intervals and hypothesis tests that are based on that approximation.

We can investigate the interplay between n 
n
 and p 
p
 and the shape of the sampling distribution by using simulations. To start off, we simulate the process of drawing 5000 samples of size 1040 from a population with a true atheist proportion of 0.1. For each of the 5000 samples we compute p ^  
p^
 and then plot a histogram to visualize their distribution.
p <- 0.1
n <- 1040
p_hats <- rep(0, 5000)

for(i in 1:5000){
  samp <- sample(c("atheist", "non_atheist"), n, replace = TRUE, prob = c(p, 1-p))
  p_hats[i] <- sum(samp == "atheist")/n
}

hist(p_hats, main = "p = 0.1, n = 1040", xlim = c(0, 0.18))

These commands build up the sampling distribution of p ^  
p^
 using the familiar for loop. You can read the sampling procedure for the first line of code inside the for loop as, "take a sample of size n 
n
 with replacement from the choices of atheist and non-atheist with probabilities p 
p
 and 1???p 
1???p
, respectively." The second line in the loop says, "calculate the proportion of atheists in this sample and record this value." The loop allows us to repeat this process 5,000 times to build a good representation of the sampling distribution.
Exercise 9
Describe the sampling distribution of sample proportions at n=1040 
n=1040
 and p=0.1 
p=0.1
. Be sure to note the center, spread, and shape.
Hint: Remember that R has functions such as mean to calculate summary statistics.

Exercise 10
Repeat the above simulation three more times but with modified sample sizes and proportions: for n=400 
n=400
 and p=0.1 
p=0.1
, n=1040 
n=1040
 and p=0.02 
p=0.02
, and n=400 
n=400
 and p=0.02 
p=0.02
. Plot all four histograms together by running the par(mfrow = c(2, 2)) command before creating the histograms. You may need to expand the plot window to accommodate the larger two-by-two plot. Describe the three new sampling distributions. Based on these limited plots, how does n 
n
 appear to affect the distribution of p ^  
p^
? How does p 
p
 affect the sampling distribution?


Once you're done, you can reset the layout of the plotting window by using the command par(mfrow = c(1, 1)) command or clicking on "Clear All" above the plotting window (if using RStudio). Note that the latter will get rid of all your previous plots.
Exercise 11If you refer to Table 6, you'll find that Australia has a sample proportion of 0.1 on a sample size of 1040, and that Ecuador has a sample proportion of 0.02 on 400 subjects. Let's suppose for this exercise that these point estimates are actually the truth. Then given the shape of their respective sampling distributions, do you think it is sensible to proceed with inference and report margin of errors, as the reports does?



